"""init schema

Revision ID: 85b9abf044c0
Revises: 
Create Date: 2025-08-08 11:49:45.481586

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '85b9abf044c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=False),
    sa.Column('before_hash', sa.String(length=64), nullable=True),
    sa.Column('after_hash', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.String(length=10), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orgnr', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('bas_chart_version', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_orgnr'), 'organizations', ['orgnr'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('personnummer_hash', sa.String(length=128), nullable=True),
    sa.Column('bankid_subject', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('mfa', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_bankid_subject'), 'users', ['bankid_subject'], unique=False)
    op.create_table('fiscal_years',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('k2_k3', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('storage_uri', sa.String(length=500), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_hash_sha256'), 'documents', ['hash_sha256'], unique=False)
    op.create_table('verifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=True),
    sa.Column('immutable_seq', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('counterparty', sa.String(length=200), nullable=True),
    sa.Column('document_link', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifications_immutable_seq'), 'verifications', ['immutable_seq'], unique=False)
    op.create_index(op.f('ix_verifications_org_id'), 'verifications', ['org_id'], unique=False)
    op.create_table('entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('verification_id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=10), nullable=False),
    sa.Column('debit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('credit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('dimension', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entries_verification_id'), 'entries', ['verification_id'], unique=False)
    op.create_table('extracted_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_fields_document_id'), 'extracted_fields', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_fields_document_id'), table_name='extracted_fields')
    op.drop_table('extracted_fields')
    op.drop_index(op.f('ix_entries_verification_id'), table_name='entries')
    op.drop_table('entries')
    op.drop_index(op.f('ix_verifications_org_id'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_immutable_seq'), table_name='verifications')
    op.drop_table('verifications')
    op.drop_index(op.f('ix_documents_hash_sha256'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('fiscal_years')
    op.drop_index(op.f('ix_users_bankid_subject'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_orgnr'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('compliance_flags')
    op.drop_table('audit_log')
    # ### end Alembic commands ###


